# Generated by Django 3.1.4 on 2020-12-08 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='valid_until',
            field=models.DateField(default=datetime.date(2020, 1, 1), verbose_name='Valid Until'),
        ),
    ]
