# Generated by Django 3.1.4 on 2020-12-08 13:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_until', models.DateField(default=datetime.date(2020, 1, 1), verbose_name='Valid Until')),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('paid_on', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Finance Summary',
                'verbose_name_plural': 'Finance Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('teachers.teachersalary',),
        ),
    ]
